name: 2wp-app build

on:
  push:

jobs:
  checkout-and-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Build project
        run: |
          npm ci
          npm run build

      - name: Unit test
        run: |
          npm run test:unit
