name: 2wp-app deploy UI for TestNet

on:
  pull_request:
    branches:
      - master
    types: [closed] 

jobs:
  checkout-and-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get tag name.
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: >
          VUE_APP_COIN=${{ secrets.TESTNET_VUE_APP_COIN }} 
          VUE_APP_MANIFEST_EMAIL=${{ secrets.TESNET_VUE_APP_MANIFEST_EMAIL }}
          VUE_APP_MANIFEST_APP_URL=${{ secrets.TESTNET_VUE_APP_MANIFEST_APP_URL }}
          VUE_APP_API_BASE_URL=${{ secrets.TESTNET_VUE_APP_API_BASE_URL }}
          VUE_APP_RSK_NODE_HOST=${{ secrets.TESTNET_VUE_APP_NODE_HOST }}
          npm run-script build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TESTNET_AWS_REGION }}

      - name: Deploy site to S3
        run: |
          aws s3 sync --delete --only-show-errors dist/ ${{ secrets.TESTNET_S3_BUCKET }}
           
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
